# .github/workflows/push.yml
name: Push to Replicate
on: { workflow_dispatch: {} }  # run it manually from the Actions tab

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}
      - run: cog push
